version: 2

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/project/home


attach_workspace: &attach_workspace
  attach_workspace:
      at: ~/project

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
      root: ~/project
      paths:
        - home

jobs:

  install:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ checksum "yarn.lock" }}
            - v1-node-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - *persist_to_workspace

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn danger ci
      - run: yarn lint

  type:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn type

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn test
    
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn build
      - store_artifacts:
          path: dist/index.js
      - store_artifacts:
          path: dist/index.nomodule.js

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - type:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
