version: 2

jobs:

  lint:
    docker:
      - image: circleci/node:9@sha256:01ced0abe8b143d0583aec4f8d23eec5fed57279ff251521fc310483f3b0bd13
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn danger ci
      - run: yarn lint

  type:
    docker:
      - image: circleci/node:9@sha256:01ced0abe8b143d0583aec4f8d23eec5fed57279ff251521fc310483f3b0bd13
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn type

  test:
    docker:
      - image: circleci/node:9@sha256:01ced0abe8b143d0583aec4f8d23eec5fed57279ff251521fc310483f3b0bd13
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
    
  build:
    docker:
      - image: circleci/node:9@sha256:01ced0abe8b143d0583aec4f8d23eec5fed57279ff251521fc310483f3b0bd13
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - "lint"
      - "type"
      - "test"
      - "build"
